@host = http://localhost:3000

### get chats of user
@userId = 1
GET {{host}}/chats/user/{{userId}}
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3MjE4NTMxOTUsImV4cCI6MTcyMTg1MzI1NX0.AFbAKp08JaJ_c_XmucoSqJuCDViHGJnzIsS3BHZ5JuY

### create chat between users
POST {{host}}/chats HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3MjE4NTMxOTUsImV4cCI6MTcyMTg1MzI1NX0.AFbAKp08JaJ_c_XmucoSqJuCDViHGJnzIsS3BHZ5JuY

{
    "senderId":1,
    "receiverId":2
}

### invite user to chat
POST {{host}}/chats/invite
Content-Type: application/json

{
    "senderId":1,
    "invitedId":3,
    "chatId":1
}

###
GET {{host}}/chats/test
Content-Type: application/json