@host = http://localhost:3000

### send message to chat
POST {{host}}/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGVzdDEiLCJpYXQiOjE3MjE4NTMzODQsImV4cCI6MTcyMTg1Njk4NH0.yBGb1Dba0gVetrq3JVsx-svKJ3xrNW06R4vfQp1e3YE

{
    "chatId":1,
    "senderId":2,
    "text":"a to druga"
}

### get all message from the chat
GET {{host}}/messages/chat/1/user/1 HTTP/1.1
Content-Type:  application/json