@host = http://localhost:3000

### register user
POST {{host}}/users/register
Content-Type: application/json

{
    "userName": "kamil",
    "password": "password"
}

### login user
POST {{host}}/users/login
Content-Type: application/json

{
    "userName": "kamil",
    "password": "password"
}